### ISSUE TITLE
@apply causes css scoping issues

### ISSUE THREAD

**Issue by pengying** [PolymerLabs/css-slam#1]
I have: 

```
:host {
  ...
  @apply(--layout-scroll);
}

.more-css {
  ...
}

```

That's getting slammed into

```
:host {
  ...
  @apply (--layout-scroll);.more-css {
  ...
  }
}
```

**Comment by ebidel** [comment]
@azakus @cdata we ran into this with IOWA

**Comment by rubenlg** [comment]
This has been partially fixed, but it still happens if the @apply statement is missing a trailing comma. Here is a simple repro case:

```css
button {
  @apply(--whatever)
}
div {
  color: red;
}
```

And the output is: `button{@apply (--whatever);div{color:red;}}`

**Comment by azakus** [comment]
Released 2.0.1 with this fix.

**Comment by rubenlg** [comment]
Thanks for the prompt fix!

**Comment by rubenlg** [comment]
I'm afraid this is not yet fixed. I just installed css-slam@2.0.1 in a clean npm project and I still reproduce the same behavior listed above, the div gets embedded inside the button block:
`button{@apply (--whatever);div{color:red;}}`

**Comment by azakus** [comment]
Ah, simple regex fail. I've modified the test to include all the various ways to space the `@apply` with parens, and i'll push that as 2.0.2.
