### ISSUE TITLE
Release new version to update dom5?

### ISSUE THREAD

**Issue by BorntraegerMarc** [PolymerLabs/css-slam#11]
According to this commit the update dom5 to v2, include parse5 already happened: https://github.com/PolymerLabs/css-slam/commit/98fadabd5be6446c973c4356b387d994ca7f9ba7

But it's unreleased. We have a `--flat` yarn install and also depend on `polymer-build@2.0.0` which uses `dom5@2.3.0`

That is why we need to resolve `dom5` to at least version 2.0.0 but doing so causes build errors for css-slam:
![image](https://user-images.githubusercontent.com/7549295/30294219-9cf93108-973c-11e7-89a0-04f24b6fc078.png)

So I think all errors could be resolved if this lib would get the dom5 v2 update. Could somebody (maybe @azakus 😄 ) release a new version with the updated dependencies?

**Comment by azakus** [comment]
Ooops, looks like this was already updated to dom5 v2 in master a while ago, but never released.
